language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
script:
    - python manage.py test


# deploy:
#   provider: heroku
#   api_key: $HEROKU_API_KEY
#   app: pizza-marko
#   run: python manage.py runserver
#   on: master
