# Generated by Django 2.0.3 on 2019-02-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Food')),
                ('topping1', models.CharField(max_length=64)),
                ('topping2', models.CharField(max_length=64)),
                ('topping3', models.CharField(max_length=64)),
            ],
            bases=('orders.food',),
        ),
    ]
