# Generated by Django 2.0.3 on 2019-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190217_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='side',
            field=models.CharField(default='whole', max_length=64),
        ),
    ]
