# Generated by Django 2.0.3 on 2019-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190219_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(default='large', max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='Dirt', max_length=64),
        ),
    ]
