# Generated by Django 2.0.3 on 2019-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_topping_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping3',
            field=models.CharField(max_length=64),
        ),
    ]
