# Generated by Django 2.0.3 on 2019-02-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='food_ptr',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
