# Generated by Django 2.0.3 on 2019-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Food')),
            ],
            bases=('orders.food',),
        ),
        migrations.CreateModel(
            name='Platters',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Food')),
                ('size', models.CharField(default='Antipasto', max_length=64)),
            ],
            bases=('orders.food',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Food')),
            ],
            bases=('orders.food',),
        ),
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
        migrations.AddField(
            model_name='pasta',
            name='sub1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub', to='orders.Sub'),
        ),
    ]
