# Generated by Django 2.0.3 on 2019-03-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_food_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platters',
            new_name='Platter',
        ),
    ]
