# Generated by Django 2.0.3 on 2019-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190304_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
