# Generated by Django 2.0.3 on 2019-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='specialInstructions',
            field=models.CharField(default='No special instructions', max_length=640),
        ),
    ]
