# Generated by Django 2.0.3 on 2019-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_food_specialinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.BooleanField(default=False),
        ),
    ]
