# Generated by Django 2.0.3 on 2019-04-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190324_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.CharField(default='Pending...', max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='priceLarge',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='food',
            name='priceSmall',
            field=models.FloatField(default=1000),
        ),
    ]
