# Generated by Django 2.0.3 on 2019-05-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190406_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Food')),
                ('size', models.CharField(default='2 dl', max_length=64)),
            ],
            bases=('orders.food',),
        ),
    ]
