# Generated by Django 2.1.5 on 2019-09-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_beverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='food_ptr',
        ),
        migrations.DeleteModel(
            name='Beverage',
        ),
    ]
