# Generated by Django 2.1.5 on 2020-01-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20190914_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='newFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(default='Dirt', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='newPizza',
            fields=[
                ('newfood_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.newFood')),
            ],
            bases=('orders.newfood',),
        ),
        migrations.CreateModel(
            name='newTopping',
            fields=[
                ('newfood_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.newFood')),
                ('_side', models.CharField(default='whole', max_length=64)),
            ],
            bases=('orders.newfood',),
        ),
    ]
