# Generated by Django 2.1.5 on 2020-01-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_newfood_newpizza_newtopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.newTopping'),
        ),
        migrations.AddField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.newTopping'),
        ),
        migrations.AddField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.newTopping'),
        ),
    ]
