# Generated by Django 2.1.5 on 2020-01-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200121_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newtopping',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
    ]
