# Generated by Django 2.1.5 on 2020-01-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0028_auto_20200124_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_smallRegular', models.FloatField(default=5)),
                ('_largeRegular', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_size', models.CharField(default='small', max_length=64)),
                ('_quantity', models.IntegerField(default=1)),
                ('_price', models.FloatField(blank=True, null=True)),
                ('_total', models.FloatField(blank=True, null=True)),
                ('_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood')),
                ('_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_status', models.CharField(default='Open', max_length=64)),
                ('_items', models.ManyToManyField(related_name='items', to='orders.NewFood')),
            ],
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newtopping',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.CreateModel(
            name='PizzaPrice',
            fields=[
                ('foodprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.FoodPrice')),
                ('_small1topping', models.FloatField(default=6)),
                ('_large1topping', models.FloatField(default=11)),
                ('_small2toppings', models.FloatField(default=7)),
                ('_large2toppings', models.FloatField(default=12)),
                ('_small3toppings', models.FloatField(default=8)),
                ('_large3toppings', models.FloatField(default=13)),
                ('_smallSpecial', models.FloatField(default=9)),
                ('_largeSpecial', models.FloatField(default=14)),
            ],
            bases=('orders.foodprice',),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood'),
        ),
    ]
