# Generated by Django 2.1.5 on 2020-01-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200125_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprice',
            name='_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='item',
            name='_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='item',
            name='_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.FoodPrice'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newsalad',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newtopping',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='order',
            name='_items',
            field=models.ManyToManyField(related_name='items', to='orders.NewFood'),
        ),
    ]
