# Generated by Django 2.1.5 on 2020-01-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200125_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='_size',
        ),
        migrations.RemoveField(
            model_name='item',
            name='_total',
        ),
        migrations.AddField(
            model_name='newfood',
            name='_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newfood',
            name='_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.FoodPrice'),
        ),
        migrations.AddField(
            model_name='newfood',
            name='_size',
            field=models.CharField(default='small', max_length=64),
        ),
        migrations.AlterField(
            model_name='foodprice',
            name='_name',
            field=models.CharField(default='FoodPrice', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newfood',
            name='_name',
            field=models.CharField(default='Regular Pizza', max_length=64),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newsalad',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newtopping',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
    ]
