# Generated by Django 2.1.5 on 2020-02-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20200215_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPizzaNoTopping',
            fields=[
                ('newfood_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood')),
            ],
            bases=('orders.newfood',),
        ),
        migrations.AlterField(
            model_name='item',
            name='_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping13', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping23', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping33', to='orders.NewTopping'),
        ),
        migrations.AlterField(
            model_name='newpizza',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newsalad',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.AlterField(
            model_name='newtopping',
            name='newfood_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewFood'),
        ),
        migrations.CreateModel(
            name='NewPizza1Topping',
            fields=[
                ('newpizzanotopping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewPizzaNoTopping')),
            ],
            bases=('orders.newpizzanotopping',),
        ),
        migrations.CreateModel(
            name='NewPizza2Toppings',
            fields=[
                ('newpizza1topping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewPizza1Topping')),
            ],
            bases=('orders.newpizza1topping',),
        ),
        migrations.AddField(
            model_name='newpizza1topping',
            name='_topping1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.NewTopping'),
        ),
        migrations.CreateModel(
            name='NewPizza3Toppings',
            fields=[
                ('newpizza2toppings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewPizza2Toppings')),
            ],
            bases=('orders.newpizza2toppings',),
        ),
        migrations.AddField(
            model_name='newpizza2toppings',
            name='_topping2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.NewTopping'),
        ),
        migrations.CreateModel(
            name='NewPizzaSpecialInstructions',
            fields=[
                ('newpizza3toppings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NewPizza3Toppings')),
                ('_specialInstructions', models.CharField(blank=True, max_length=640, null=True)),
            ],
            bases=('orders.newpizza3toppings',),
        ),
        migrations.AddField(
            model_name='newpizza3toppings',
            name='_topping3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.NewTopping'),
        ),
    ]
